server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "payment_service"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

logger:
  level: "info"
  format: "json"
  output_path: "stdout"

app:
  name: "payment-service"
  version: "1.0.0"
  environment: "development"